:snake: Working on #13 & #14, Tor & Nginx, update python tests

diff --git a/delegito/Dockerfile b/delegito/Dockerfile
--- a/delegito/Dockerfile
+++ b/delegito/Dockerfile
@@ -1,12 +1,18 @@
 FROM python:2.7
 MAINTAINER Cameron Whiting "thetoxicarcade@gmail.com"
-RUN apt-get update -qq
-RUN apt-get install -qqy build-essential libssl-dev libffi-dev python-dev 1>/dev/null
-RUN bash -c "pip install flask redis pymongo nose2 PGPy pyjwt celery stem" 1>/dev/null
+RUN apt-get update -qq && \
+    apt-get install -qqy build-essential libssl-dev libffi-dev python-dev tor 1>/dev/null
+ADD requirements.txt /
+RUN pip install -r requirements.txt 1>/dev/null && \
+    pip install nose2 setuptools-lint 1>/dev/null
 ADD . /code/delegito
 WORKDIR /code
-RUN mv delegito/setup.py setup.py && pip install setuptools-lint && mv delegito/.pylintrc .pylintrc
-RUN python setup.py build && python setup.py test && python setup.py install && python setup.py lint || echo "Lint failing..."
+RUN mv delegito/setup.py setup.py && \
+    mv delegito/.pylintrc .pylintrc && \
+    python setup.py build && \
+    python setup.py test && \
+    python setup.py install && \
+    python setup.py lint || echo "Lint failing..."
 #ENV DEBIAN_FRONTEND noninteractive
 #RUN apt-get update && apt-get install -y apt-transport-https && apt-get upgrade -y --install-recommends
 #RUN sudo apt-get install -y --install-recomends python-pip python-dev
